import localFont from "next/font/local";
import "@/styles/globals.scss";
import Header from "@/components/layout/header/header";
import Footer from "@/components/layout/footer/footer";
import { UserProvider } from "@/context/user-context";
import getUser from "@/services/get-user";
import UserContextInitializer from "@/components/account/user-context-initializer";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUser();
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <UserContextInitializer user={user?.success ? user.data : null} />
          <Header />
          {children}
          <Footer />
          <div id="reusablePortal" />
        </UserProvider>
      </body>
    </html>
  );
}
